### ISSUE TITLE
Problem with python interface

### ISSUE THREAD

**Issue by AlOa** [darioizzo/d-CGP#16] opened 2016-10-31 17:30 UTC
Hi,
I can use d-CGP with c++, but when I tried to use the python interface I got the following error:

lib/python2.7/site-packages/dcgpy/_core.so: undefined symbol: _ZN5boost6python7objects23register_dynamic_id_auxENS0_9type_infoEPFNSt3__14pairIPvS2_EES5_E

I check the _core.so with ldd and it is linked with libpython2.7.so and boost python.
Have you any idea on which is the cause of this error?
Thank
               Alberto

**Comment by darioizzo** [comment] 2016-11-01 08:16
I guess this happens when you try to import dcgpy right?

I would need to reproduce it here on our servers to understand ... can you give me

1) your OS
2) the compiler you use
3) the output of cmake ../

thanks ..

Dario

**Comment by AlOa** [comment] 2016-11-02 08:56
Hi,

> 1) your OS

OpenSuse 13.2

> 2) the compiler you use

clang version 3.5.0 

> 3) the output of cmake ../

-- The C++ compiler ID is: Clang
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wshadow' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Werror' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wall' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wextra' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wnon-virtual-dtor' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Failed
-- Disabling the '-Wnoexcept' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Failed
-- Disabling the '-Wlogical-op' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wdeprecated' debug compiler flag.
-- Performing Test YACMA_CHECK_CXX_FLAG
-- Performing Test YACMA_CHECK_CXX_FLAG - Success
-- Enabling the '-ftemplate-depth=1024' compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-pedantic-errors' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wdisabled-optimization' debug compiler flag.
-- Performing Test YACMA_CHECK_CXX_FLAG
-- Performing Test YACMA_CHECK_CXX_FLAG - Success
-- Enabling the '-fvisibility-inlines-hidden' compiler flag.
-- Performing Test YACMA_CHECK_CXX_FLAG
-- Performing Test YACMA_CHECK_CXX_FLAG - Success
-- Enabling the '-fvisibility=hidden' compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-ftemplate-backtrace-limit=0' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-fstack-protector-all' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Success
-- Enabling the '-Wodr' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Failed
-- Disabling the '-Wsuggest-final-types' debug compiler flag.
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG
-- Performing Test YACMA_CHECK_DEBUG_CXX_FLAG - Failed
-- Disabling the '-Wsuggest-final-methods' debug compiler flag.
-- Thread library: -lpthread
-- POSIX threads detected.
-- Enabling the -pthread compiler flag.
-- POSIX threads affinity extensions detected.
-- Extra compiler flags for threading: -pthread
-- The 'thread_local' keyword is not available.
-- Python interpreter: /usr/bin/python
-- Python libraries: /home/alberto/anaconda/lib/libpython2.7.so
-- Python include dirs: /usr/include/python2.7
-- Python library version: 2.7.12
-- Generic UNIX platform detected.
-- Python packages dir is: site-packages
-- Python modules install path: lib/python2.7/site-packages
-- NumPy includes dir: /usr/lib64/python2.7/site-packages/numpy/core/include
-- Linking boost python.
-- Linking serialization.
-- Required Boost libraries: python;serialization
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   python
--   serialization
-- Detected Boost version: 105700
-- Boost include dirs: /home/alberto/boost_1_57_0/PREFIX/include
-- Boost libraries: /home/alberto/boost_1_57_0/PREFIX/lib/libboost_python.so;/home/alberto/boost_1_57_0/PREFIX/lib/libboost_serialization.so
-- Piranha library found.
-- Piranha include dir is: /home/alberto/piranha/Release/build/include
-- Audi library found.
-- Audi include dir is: /home/alberto/piranha/Release/build/include
-- GMP library found.
-- GMP include dir is: /usr/include
-- GMP library is: /usr/lib64/libgmp.so
-- MPFR library found.
-- MPFR include dir is: /usr/include
-- MPFR library is: /usr/lib64/libmpfr.so
-- Checking MPFR version.
-- MPFR version is ok.
-- Setting up the compilation of the Python module "_core".
-- Setting up extra compiler flag "-fwrapv" for the Python module "_core".
-- Python < 3 detected, setting up extra compiler flag "-fno-strict-aliasing" for the Python module "_core".
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alberto/new_d-CGP/Release

The strange thing is that I have no problem with pyaudi which use the same boost libraries.
Thanks
                      Alberto

**Comment by darioizzo** [comment] 2016-11-02 10:18
probably irrelevant, but you use the system python, but the anaconda python library ..... could that be an issue?

**Comment by AlOa** [comment] 2016-11-02 11:14
I also tried with system python library but gives the same error.

  Alberto

**Comment by darioizzo** [comment] 2016-11-02 12:33
Can you post the list of libraries _core.so links to?

**Comment by AlOa** [comment] 2016-11-02 12:58
Yes,

        linux-vdso.so.1 (0x00007ffe379e6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f503c033000)
        libmpfr.so.4 => /usr/lib64/libmpfr.so.4 (0x00007f503bdd7000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f503bb50000)
        libpython2.7.so.1.0 => /usr/lib64/libpython2.7.so.1.0
(0x00007f503b742000)
        libboost_serialization.so.1.57.0 =>
/home/alberto/boost_1_57_0/PREFIX/lib/libboost_serialization.so.1.57.0
(0x00007f503b4e1000)
        libboost_python.so.1.57.0 =>
/home/alberto/boost_1_57_0/PREFIX/lib/libboost_python.so.1.57.0
(0x00007f503b291000)
        libc++.so.1 => /usr/lib64/libc++.so.1 (0x00007f503afd1000)
        libc++abi.so.1 => /usr/lib64/libc++abi.so.1 (0x00007f503ad7b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f503aa7a000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f503a863000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f503a4b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f503c57e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f503a2b4000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f503a0b1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f5039ea8000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f5039ba0000)

**Comment by darioizzo** [comment] 2016-11-02 14:27
I am at loss here. To summarize, it seems as if _core.so cannot find the  boost::python::register_dynamic_id_aux object which should be defined in the boost python library which it is linked against.

I cannot reproduce here the problem (ubuntu and archlinux systems with python3) so its difficult to go further in the diagnosis ....

**Comment by AlOa** [comment] 2016-11-02 14:56
Ok, I will use C++ for now.
Thanks!

           Alberto

**Comment by AlOa** [comment] 2016-11-21 10:11
Hi,
at last I solved at last I solved the problem. I build dCGP.py with clang but I linked it with boost libraries builded with g++. 
Now I can import it without problems. 

```
from pyaudi import gdual_vdouble as gdual
import pyaudi
from dcgpy import expression_gdual_vdouble as expression
from dcgpy import kernel_set_gdual_vdouble as kernel_set
import numpy as np

kernels = kernel_set(["sum", "mul", "diff", "div"])()

dCGP = expression(1, 1, rows=1, cols=15, levels_back=16, arity=2, kernels=kernels, seed=np.random.randint(1233456))

x = np.linspace(0,1,10)
x = gdual(x)
dCGP([x])
```
I get the following error:

TypeError: No registered converter was able to produce a C++ rvalue of type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > from this Python object of type gdual_vdouble

**Comment by darioizzo** [comment] 2016-11-21 10:25
Ok, glad you solved it: then I will close this issue. For the new problem, can you open a new issue?

**Closed by darioizzo** 2016-11-21 10:25 UTC
